language: python
python:
  - "3.6"

sudo: required

services:
  - docker

notifications:
  email: false

before_install:
- docker pull zookeeper:3.4
- docker run -d -p 2181:2181 zookeeper:3.4

install:
  - pip install -r requirements.txt
  - pip install pytest

script: py.test tests